[workspace]

members = [
    "hedgehog-player",
    "hedgehog-library",
    "hedgehog-tui",
    "cmd-parser",
    "cmd-parser-derive",
    "cmd-parser-derive-tests",
]
default-members = ["hedgehog-tui"]
