[package]
name = "hedgehog-tui"
version = "0.1.0"
edition = "2018"

[dependencies]
crossterm = { version = "0.20", features = ["event-stream"] }
tui = { version = "0.15", features = ["crossterm"], default-features = false }
actix = "0.12"
unicode-width = "0.1"
serde = { version = "1.0", features = ["derive"] }
shlex = "1.1"
thiserror = "1.0"
bitflags = "1.3"
hedgehog-library = { path = "../hedgehog-library" }
hedgehog-player = { path = "../hedgehog-player" }

[dev-dependencies]
tempfile = "3.2"
