[variables]
dark0_hard = "1d2021"
dark0 = "282828"
dark0_soft = "32302f"
dark1 = "3c3836"
dark2 = "504945"
dark3 = "665c54"
dark4 = "7c6f64"

light0_hard = "f9f5d7"
light0 = "fbf1c7"
light0_soft = "f2e5bc"
light1 = "ebdbb2"
light2 = "d5c4a1"
light3 = "bdae93"
light4 = "a89984"

red = { bright = "fb4934", neutral = "cc241d", faded = "9d0006" }
green = { bright = "b8bb26", neutral = "98971a", faded = "79740e" }
yellow = { bright = "fabd2f", neutral = "d79921", faded = "b57614" }
blue = { bright = "83a598", neutral = "458588", faded = "076678" }
purple = { bright = "d3869b", neutral = "b16286", faded = "8f3f71" }
aqua = { bright = "8ec07c", neutral = "689d6a", faded = "427b58" }
orange = { bright = "fe8019", neutral= "d65d0e", faded= "af3a03" }

[variants.dark]
background = ["$dark0_hard", "$dark0"]
highlight = ["$dark0", "$dark0_soft"]
active = ["$dark1", "$dark2"]
divider = "$dark2"
text = ["$light1", "$light0"]
color_variants = ["neutral", "bright"]
player = "$dark2"
player_active = "$dark3"
