[package]
name = "hedgehog-player"
version = "0.1.0"
edition = "2018"

[dependencies]
gstreamer-base = "0.17"
actix = "0.12"
serde = { version = "1.0", features = ["derive"] }
cmd-parser = { path = "../cmd-parser" }

[[bin]]
name = "player-client"
path = "bin/player_client.rs"
