on:
  push:
    tags:
      - "v*"

jobs:
  build-binary:
    name: build-binary
    strategy:
      matrix:
        os: 
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cargo and tools
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev libdbus-1-dev libssl-dev libgstreamer1.0-dev 

      - name: Create an archive
        run: make archive

      - name: Upload the binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary-releases
          path: ./build
          retention-days: 1

  create-release:
    name: create-release
    runs-on: ubuntu-latest
    needs:
      - build-binary
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Get version number
        run: echo "HEDGEHOG_VERSION=$(make version)" >> $GITHUB_ENV

      - name: Download the built artifact
        uses: actions/download-artifact@v3
        with:
          name: binary-releases
          path: build

      - name: Create a Release
        uses: softprops/action-gh-release@v1
        with:
          name: Hedgehog ${{ env.HEDGEHOG_VERSION }}
          files: build/*
