on:
  pull_request:
  push:
    branches:
      - trunk

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: 
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cargo and tools
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev libdbus-1-3 libssl-dev libgstreamer1.0-dev 

      - name: Run tests
        run: cargo test --all

      - name: Run fmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all
